name: test-name

on: [push]



jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: "checkout: source repo"
      uses: actions/checkout@v3
      with:
        path: source
    - name: "checkout: target repo"
      uses: actions/checkout@v3
      with:
        path: target
        repository: 3sdd/create-pull-request-to-another-repo-target
    - name: print
      run: |
        pwd
        ls -la
    - name: create pull request
      env:
        GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
      run: gh pr create --title "プルリクエスト作成テスト" --body "プルリクエスト作成テスト　body" --base "main" --repo "3sdd/create-pull-request-to-another-repo-target"

