name: test-name

on: [push]



jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: print
      run: echo "テスト"
    - name: create pull request
      run: gh pr create --title "プルリクエスト作成テスト" --body "プルリクエスト作成テスト　body" --base "main"
