name: test-name

on: [push]


jobs:
  test-job:
    runs-on: ubuntu-latest

    permissions:
     actions: write
     checks: write
     contents: write
     deployments: write
     issues: write
     packages: write
     pull-requests: write
     repository-projects: write
     security-events: write
     statuses: write

    steps:
    - name: "checkout: source repo"
      uses: actions/checkout@v3
      with:
        path: source
    - name: "checkout: target repo"
      uses: actions/checkout@v3
      with:
        path: target
        repository: 3sdd/create-pull-request-to-another-repo-target
        ref: main
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: print
      run: |
        pwd
        cd source
        ls -la
        cd ../target
        ls -la
    - name: copy schema file
      run: cp source/schema.yml target/schema.yml
    - name: print
      run: |
        pwd
        cd source
        ls -la
        cd ../target
        ls -la
    - name: setup git config
      run: |
        git config --global user.name "3sdd"
        git config --global user.email "56486103+3sdd@users.noreply.github.com"
    - name: commit
      working-directory: target
      env:
        TARGET_REPOSITORY: 3sdd/create-pull-request-to-another-repo-target
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git remote set-url origin https://3sdd:$PERSONAL_ACCESS_TOKEN@github.com/$TARGET_REPOSITORY
        git fetch
        echo "checkout"
        git checkout test-branch
        echo "add schema"
        git add ./schema.yml
        git status
        echo "commit"
        git commit -m "updat schema"
        echo "push"
        git push origin test-branch
    - name: create pull request
      env:
        GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
      run: gh pr create --title "プルリクエスト作成テスト" --body "プルリクエスト作成テスト　body" --base "main" --repo "3sdd/create-pull-request-to-another-repo-target"

