name: test-name

on: [push]



jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: "checkout: source repo"
      uses: actions/checkout@v3
      with:
        path: source
    - name: "checkout: target repo"
      uses: actions/checkout@v3
      with:
        path: target
        repository: 3sdd/create-pull-request-to-another-repo-target
    - name: print
      run: |
        pwd
        cd source
        ls -la
        cd ../target
        ls -la
    - name: copy schema file
      run: cp source/schema.yml target/schema.yml
    - name: print
      run: |
        pwd
        cd source
        ls -la
        cd ../target
        ls -la
    - name: setup git config
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: commit
      working-directory: target
      run: |
        git add ./schema.yml
        git commit -m "updat schema"
    - name: create pull request
      env:
        GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
      run: gh pr create --title "プルリクエスト作成テスト" --body "プルリクエスト作成テスト　body" --base "main" --repo "3sdd/create-pull-request-to-another-repo-target"

