name: test-name

on:
  push:
    paths:
      - "schema.yml"

env:
  TARGET_PUSH_BRANCH_NAME: test-branch

jobs:
  test-job:
    runs-on: ubuntu-latest

    permissions:
     actions: write
     checks: write
     contents: write
     deployments: write
     issues: write
     packages: write
     pull-requests: write
     repository-projects: write
     security-events: write
     statuses: write

    steps:
    - name: "checkout: source repo"
      uses: actions/checkout@v3
      with:
        path: source
    - name: "checkout: target repo"
      uses: actions/checkout@v3
      with:
        path: target
        repository: 3sdd/create-pull-request-to-another-repo-target
        ref: main
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: copy schema file
      run: cp source/schema.yml target/schema.yml
    - name: setup git config
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
    - name: commit
      working-directory: target
      env:
        TARGET_REPOSITORY: 3sdd/create-pull-request-to-another-repo-target
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      run: |
        git remote set-url origin https://github.com/$TARGET_REPOSITORY
        git fetch
        echo "switch branch"
        git switch -c $TARGET_PUSH_BRANCH_NAME
        echo "add schema"
        git add ./schema.yml
        git status
        echo "commit"
        git commit -m "スキーマ更新"
        echo "push"
        git push origin -u $TARGET_PUSH_BRANCH_NAME
    - name: create pull request
      working-directory: target
      env:
        GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
      run: gh pr create --title "スキーマ更新" --body "更新" --base "main" --repo "3sdd/create-pull-request-to-another-repo-target"

